### ISSUE TITLE
reaper comics invalid data

### ISSUE THREAD

**Issue by blackwing12344** [KotatsuApp/kotatsu-parsers#1035]
### Source information

ReaperComics

### Kotatsu version

7.4.3

### Android version

13

### Other details

All new chapters from about 2 weeks out return invalid or corrupted data for every page, but not the chapter as a whole.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MariusAlbrecht** [comment]
can confirm. Error details are as follows:

```
java.io.IOException: Image format not supported
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:172)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:206)
	at androidx.core.view.ContentInfoCompat$$ExternalSyntheticApiModelOutline0.m(SourceFile:6)
	at com.davemorrissey.labs.subscaleview.decoder.UtilKt.BitmapRegionDecoder(SourceFile:2)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.initialiseDecoder(SourceFile:119)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.init(SourceFile:4)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1.invokeSuspend$lambda$1(SourceFile:20)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1.$r8$lambda$SPnG3AkRCEkxuG8UEQOKyncB5cU(SourceFile:1)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$loadTile$1$$ExternalSyntheticLambda0.invoke(SourceFile:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(SourceFile:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:122)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
		at org.koitharu.kotatsu.reader.domain.PageLoader.convertBimap(SourceFile:365)
		at org.koitharu.kotatsu.reader.domain.PageLoader$convertBimap$1.invokeSuspend(Unknown Source:12)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
		at kotlinx.coroutines.DispatchedTask.run(SourceFile:101)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:233)
		at android.os.Looper.loop(Looper.java:344)
		at android.app.ActivityThread.main(ActivityThread.java:8212)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

when opening the pages in the browser they get displayed. They are in the `avif` format, maybe that's not supported in the Kotatsu App?
