### ISSUE TITLE
Image format no supported 

### ISSUE THREAD

**Issue by MaSHiNiK** [KotatsuApp/kotatsu-parsers#156]
### Source information

Mangalib

### Steps to reproduce

Skullgirs (WEBTOON), None of the pages are displayed.
![Screenshot-2023-02-24-09-54-02](https://user-images.githubusercontent.com/80310257/221124377-66268a6a-b9ba-4a49-ba81-f11e63ed2b53.jpeg)

### Kotatsu version

4.4.1

### Android version

8.0

### Other details

`java.io.IOException: Image format not supported
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:125)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:156)
	at com.davemorrissey.labs.subscaleview.decoder.UtilKt.BitmapRegionDecoder(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.initialiseDecoder(SourceFile:245)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.init(SourceFile:5)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(SourceFile:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
		at org.koitharu.kotatsu.utils.ext.FileExtKt$computeSize$2.invoke(SourceFile:126)
		... 4 more
`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Please confirm if it was fixed

**Comment by MaSHiNiK** [comment]
> Please confirm if it was fixed

I'd like to... but the error hasn't gone away

**Comment by Ampnbsp** [comment]
That issue reveals in a such random titles
Kotatsu: Version 5.3.3
Android: TQ3A.230705.001.2023070500

For example:
https://mangalib.me/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi
Chapter 22

https://mangalib.me/wakabayashi-toshiyas-4koma-collection
Chapter 81.5

https://mangalib.me/sukinako-ga-megane-wo-wasureta
Chapter 46

java.io.IOException: Image format not supported
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:166)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:200)
	at androidx.core.view.ContentInfoCompat$$ExternalSyntheticApiModelOutline0.m(SourceFile:9)
	at com.davemorrissey.labs.subscaleview.decoder.UtilKt.BitmapRegionDecoder(SourceFile:2)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SourceFile:177)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(SourceFile:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke$4(SourceFile:66)
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke(SourceFile:9)
		... 4 more

**Comment by Koitharu** [comment]
Probably fixed in 74a20455f25d4cdb4efccaf23ab445180eb86069

**Comment by davvarrr** [comment]
now its fixed, if you get the same error again open another issuse
