### ISSUE TITLE
Image format not supported

### ISSUE THREAD

**Issue by Ampnbsp** [KotatsuApp/kotatsu-parsers#207]
### Source information

mangalib.me

### Steps to reproduce

https://mangalib.me/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi

For example chapter 22 does not load.

### Kotatsu version

5.3.3

### Android version

TQ3A.230705.001.2023070500

### Other details

java.io.IOException: Image format not supported
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:166)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:200)
	at androidx.core.view.ContentInfoCompat$$ExternalSyntheticApiModelOutline0.m(SourceFile:9)
	at com.davemorrissey.labs.subscaleview.decoder.UtilKt.BitmapRegionDecoder(SourceFile:2)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SourceFile:177)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(SourceFile:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke$4(SourceFile:66)
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke(SourceFile:9)
		... 4 more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Ampnbsp** [comment]
Closing as a duplicate.
