### ISSUE TITLE
TuMangaOnline stopped working

### ISSUE THREAD

**Issue by INFZeroT** [KotatsuApp/kotatsu-parsers#277]
### Source information

TuMangaOnline

### Steps to reproduce

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:93)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:132)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:254)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:1010)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:231)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:336)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:94)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:654)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:503)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:423)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:351)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 35 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 48 more

### Kotatsu version

6.1.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
duplicate of #236  
Enabling igonre SSL errors in the settings for now solves the problem.
