### ISSUE TITLE
Tumangaonline Error

### ISSUE THREAD

**Issue by ReigenJD** [KotatsuApp/kotatsu-parsers#495]
### Source information

TuMangaOnline

### Steps to reproduce

When I try to read a manga in this source server, the images don't charge.
(Sorry for my English)

This is te error

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:101)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:122)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:288)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:902)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:430)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:139)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:176)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:11)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:85)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:207)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:131)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:95)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:661)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 35 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 48 more
![Screenshot_2024-01-17-00-52-54-294_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/156881106/1a2b5106-6a3d-4d59-bbb4-7a862cf65291)

### Kotatsu version

6.6.3

### Android version

Android 11

### Other details

I don't know if this is an error only on my smartphone, but is the only source server where this happen.
If is my fault, pls tell what should I do, thank u.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#236
